use_frameworks!

platform :ios, '9.0'

target 'JAConfigBase_Example' do
  pod 'JAConfigBase', :path => '../'

  target 'JAConfigBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
